### ISSUE TITLE
Is this project still alive ? Couple bugs I ran into.

### ISSUE THREAD

**Issue by Windspar** [Dgame/Dgame#70]
Just trying to run the first tutorial.
```D
import Dgame.Window.Window;
import Dgame.Graphic.Color;
import Dgame.System.StopWatch;

void main()
{
    Window window = Window(800, 600, "Dgame Window");
    window.setClearColor(Color4b.Blue);
    window.clear();
    window.display();
    StopWatch.wait(2000);
}
```
DGame 6.5 on linux-antergos(arch-linux)
Line 59 in Dgame/Math/Vertex.d. `this.color = col;`
I change it to `this.color = Color4f(col);`

Then i get this error.
```
Performing "debug" build using /usr/bin/dmd for x86_64.
derelict-util 2.0.6: target for configuration "library" is up to date.
derelict-gl3 1.0.24: target for configuration "library" is up to date.
derelict-sdl2 1.9.7: target for configuration "library" is up to date.
dgame 0.6.5: target for configuration "lib" is up to date.
app ~master: target for configuration "application" is up to date.
To force a rebuild of up-to-date targets, run again with --force.
Running ./app 
SDL version: 2.0.8
core.exception.AssertError@source/Dgame/Internal/Error.d(17): 
----------------
??:? _d_assert_msg [0x2e4bed5e]
source/Dgame/Internal/Error.d:17 nothrow @nogc void Dgame.Internal.Error.assert_fmt!(const(char)*).assert_fmt(bool, immutable(char)[], const(char)*) [0x2e48d031]
source/Dgame/Window/Internal/Init.d:111 void Dgame.Window.Internal.Init._initSDL() [0x2e490f73]
source/Dgame/Window/Window.d:141 ref Dgame.Window.Window.Window Dgame.Window.Window.Window.__ctor(const(Dgame.Math.Rect.Rect), immutable(char)[], uint, const(Dgame.Window.GLContextSettings.GLContextSettings)) [0x2e48936e]
source/Dgame/Window/Window.d:121 ref Dgame.Window.Window.Window Dgame.Window.Window.Window.__ctor(uint, uint, immutable(char)[], uint, const(Dgame.Window.GLContextSettings.GLContextSettings)) [0x2e48927a]
source/app.d:7 _Dmain [0x2e488968]
Program exited with code 1
[drake@hacker 0. Window]$ 
```

**Comment by Dgame** [comment]
It's still alive, but not actively maintained since I'm not programming that much in D anymore as I've used to be. I've fixed the conversion bug and fixed the error of the assertion error ;). I suppose the error was caused due to a large stacktrace. It looks like the real error happened here: https://github.com/Dgame/Dgame/blob/master/source/Dgame/Window/Internal/Init.d#L111
It seems that your SDL is missing the required ogg and mp3 support.

**Comment by Windspar** [comment]
They are install. An I still receive error. It looks like a derelict bug.
```
SDL version: 2.0.8
core.exception.AssertError@/home/drake/.dub/packages/dgame-0.6.6/dgame/source/Dgame/Internal/Error.d(36): Error: Failed to init the required ogg and mp3 support: OGG support not available
```
My c program runs fine.
```C
#include <stdio.h>
#include "SDL.h"
#include "SDL_mixer.h"

// gcc -o sdl_window sdl_window.c -I/usr/include/SDL2 -lSDL2 -lSDL2_mixer

int main() {
    if (SDL_Init(SDL_INIT_VIDEO|SDL_INIT_AUDIO) != 0) {
        SDL_Log("Unable to initialize SDL: %s", SDL_GetError());
        return 1;
    }

    int mixFlags = MIX_INIT_OGG | MIX_INIT_MP3;
    int mixInit = Mix_Init(mixFlags);
    if(mixInit & mixFlags != mixFlags) {
        SDL_Log("Unable to initialize Mixer ogg or mp3: %s", Mix_GetError());
        SDL_Quit();
        return 1;
    }

    printf("Everything is good");
    SDL_Quit();
    return 0;
}
```

my derelict sdl2 program get same error.
```D
import std.stdio : writeln;
import derelict.sdl2.sdl;
import derelict.sdl2.mixer;

void main() {
    DerelictSDL2.load();
    if (SDL_Init(SDL_INIT_VIDEO|SDL_INIT_AUDIO) != 0) {
        writeln("Unable to initialize SDL: ", SDL_GetError());
        return;
    }

    DerelictSDL2Mixer.load();
    int mixFlags = MIX_INIT_OGG | MIX_INIT_MP3;
    int mixInit = Mix_Init(mixFlags);
    if ((mixInit & mixFlags) != mixFlags) {
        writeln("Unable to initialize Mixer ogg or mp3: ", Mix_GetError());
        SDL_Quit();
        return;
    }

    Mix_Quit();
    SDL_Quit();
}
```

**Comment by Dgame** [comment]
Strange. But aldacron is quick in fixing such stuff, just open an issue.

**Comment by Windspar** [comment]
Never mine. 
`if(mixInit & mixFlags != mixFlags)`
forgot () around mixInit & mixFlags
my c program get the same error.

**Comment by Dgame** [comment]
Omg, I got caught in the same trap. Silly me. Well, I could change that requirement since sound support is not your concern als long as you don't use the Sound package. But that would have to wait until next week.

**Comment by Windspar** [comment]
Found the bug. Fix is open audio before Mix_Init.
No more error. 
```D
import std.stdio : writeln;
import derelict.sdl2.sdl;
import derelict.sdl2.mixer;

void main() {
    DerelictSDL2.load();
    if (SDL_Init(SDL_INIT_VIDEO|SDL_INIT_AUDIO) != 0) {
        writeln("Unable to initialize SDL: ", SDL_GetError());
        return;
    }

    DerelictSDL2Mixer.load();

    if(Mix_OpenAudio(44100, MIX_DEFAULT_FORMAT, 2, 1024)==-1) {
        SDL_Quit();
        return;
    }

    int mixFlags = MIX_INIT_OGG | MIX_INIT_MP3;
    int mixInit = Mix_Init(mixFlags);
    if ((mixInit & mixFlags) != mixFlags) {
        if ((mixInit & MIX_INIT_OGG) !=  MIX_INIT_OGG)
            writeln("Unable to find ogg");

        if ((mixInit & MIX_INIT_MP3) !=  MIX_INIT_MP3)
            writeln("Unable to find mp3");

        writeln(Mix_GetError());
        SDL_Quit();
        return;
    }

    Mix_Quit();
    SDL_Quit();
}
```

**Comment by Windspar** [comment]
I change the order of open audio in dgame/window/internal/init.d. My program runs now. Thanks for your time.
```D
// Initialize SDL_mixer
    result = Mix_OpenAudio(22050, MIX_DEFAULT_FORMAT, MIX_DEFAULT_CHANNELS, 4096);
    assert_fmt(result == 0, "Warning: Could not open Mix_OpenAudio: %s\n", Mix_GetError());

    result = Mix_Init(MIX_INIT_OGG | MIX_INIT_MP3);
    assert_fmt(result != 0, "Error: Failed to init the required ogg and mp3 support: %s\n", Mix_GetError());

    if ((result & MIX_INIT_OGG) == 0)
        print_fmt("Warning: No ogg support: %s\n", Mix_GetError());
    else if ((result & MIX_INIT_MP3) == 0)
        print_fmt("Warning: No mp3 support: %s\n", Mix_GetError());
```

**Comment by Dgame** [comment]
Seems to work under SDL 2.0.3 & 2.0.4 as well, thanks for your work!
